name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Migrate
      run: |
        cd tickets_with_miles
        python manage.py migrate

    - name: Run unit tests
      run: |
        cd tickets_with_miles
        coverage run --source=. manage.py test flights/tests/unit

    - name: Run E2E tests
      run: |
        cd tickets_with_miles
        coverage run --append --source=. manage.py test flights/tests/e2e

    - name: Combine & generate coverage report
      run: |
        cd tickets_with_miles
        coverage combine
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./tickets_with_miles/coverage.xml
        fail_ci_if_error: true
